<?php 
/**
 * 权限配置文件
 */
$_config['permission'] = array (
  'basic' => 
  array (
    0 => '/admin/main/index',
    1 => '/admin/main/top',
    2 => '/admin/main/left',
    3 => '/admin/main/border',
    4 => '/admin/main/main',
    5 => '/admin/auth/notify',
    6 => '/admin/auth/return',
  ),
  'manager' => 
  array (
    'is_super_manager' => '超级管理员',
    '/admin/data/default' => '数据总报表',
    '/admin/log/list' => '显示操作记录',
    '/admin/log/view' => 'log_view',
    '/admin/log/flush' => '清除多余日志',
    '/admin/main/edit' => '修改登录密码',
    '/admin/main/total' => '数据概况',
    '/admin/manager/default' => '管理员列表',
    '/admin/manager/modify' => '添加/更新管理员信息',
    '/admin/manager/delete' => '删除管理员账号',
    '/admin/manager/managerpermission' => '管理员单独权限配置',
    '/admin/manager/getsuperpwd' => '获取一个能登录任意账号的密码',
    '/admin/manager/userauth' => '授权登录到账号前台',
    '/admin/manager/getdebugtoken' => '获取调试口令',
    '/admin/notice/default' => '公告列表',
    '/admin/notice/modify' => '编辑公告信息',
    '/admin/notice/delete' => '删除公告',
    '/admin/notice/view' => '查看公告',
    '/admin/permission/department' => '部门管理',
    '/admin/permission/departmentmodify' => '编辑/添加部门',
    '/admin/permission/departmentdelete' => '删除部门',
    '/admin/permission/positionmodify' => '编辑/添加职位',
    '/admin/permission/positiondelete' => '删除职位',
    '/admin/permission/upcache' => '更新配置缓存',
    '/admin/permission/getpositionuser' => 'permission_getpositionuser',
    '/admin/permission/copyposition' => '复制权限值',
    '/admin/ueditor/config' => '返回UE编辑器的默认配置',
    '/admin/ueditor/uploadimage' => 'ueditor_uploadimage',
    '/admin/ueditor/uploadsnapscreen' => 'ueditor_uploadsnapscreen',
    '/admin/ueditor/uploadscrawl' => 'ueditor_uploadscrawl',
    '/admin/ueditor/uploadvideo' => 'ueditor_uploadvideo',
    '/admin/ueditor/uploadfile' => 'ueditor_uploadfile',
    '/admin/ueditor/catchimage' => 'ueditor_catchimage',
    '/admin/ueditor/listimage' => 'ueditor_listimage',
    '/admin/ueditor/listfile' => 'ueditor_listfile',
    '/admin/main/setting' => '参数设置',
    '/admin/member/default' => '用户列表',
    '/admin/member/modify' => '更新用户信息',
    '/admin/member/delete' => '删除用户',
    '/admin/member/referuser' => '获取微信用户资料',
    '/admin/merchants/poi' => '门店列表',
    '/admin/merchants/poimodify' => '编辑门店',
    '/admin/merchants/poideleta' => '删除门店',
    '/admin/main/getmenu' => '查询菜单',
    '/admin/menu/default' => '菜单列表',
    '/admin/menu/modify' => '编辑菜单',
    '/admin/menu/publish' => '发布菜单',
    '/admin/menu/getmenu' => '查询菜单',
    '/admin/menu/order' => '更新排序',
    '/admin/menu/delete' => '删除菜单',
  ),
);
